name: Deploy to Vercel
on:
  push:
    branches:
      - main  # 메인 브랜치에 푸시될 때 실행
  pull_request:
    branches:
      - main  # 메인 브랜치로의 PR에서 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Print debug info
        run: |
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo "Working directory: $(pwd)"
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          ls -la
          
      - name: Install dependencies
        run: |
          npm ci
          npm list --depth=0
        
      - name: Build project
        run: |
          echo "Starting build..."
          npm run build
          echo "Build completed"
          ls -la .next
        
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
        
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Deploy to Vercel
        run: |
          echo "Deploying to Vercel..."
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} 